spring.application.name=GalimbureProject

spring.datasource.url=jdbc:postgresql://student_database_xxaq_user:gmWkON4i9OP5vLtS8BAD4iuBuElFitEs@dpg-d8psfeq8qa3s73c5j0qg-a.singapore-postgres.render.com/student_database_xxaq
spring.datasource.username=student_database_xxaq_user
spring.datasource.password=gmWkON4i9OP5vLtS8BAD4iuBuElFitEs

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
